export const examples = [
  { id: 'clean', name: 'A clean choice', kind: 'LL(1)', focus: 'S', look: 'a', input: 'a c',
    source: 'S -> a A | b B\nA -> c | ε\nB -> d',
    note: 'At S, a chooses the first branch and b chooses the second. At A, c continues; $ chooses the empty alternative.' },
  { id: 'first-first', name: 'Two branches start with a', kind: 'FIRST / FIRST', focus: 'S', look: 'a', input: 'a b',
    source: 'S -> a b | a c',
    note: 'Both alternatives begin with a. The grammar is unambiguous, but one token cannot choose between them. Factoring delays the choice.' },
  { id: 'double-empty', name: 'Two ways to disappear', kind: 'Two nullable branches', focus: 'S', look: '$', input: '',
    source: 'S -> A | B\nA -> ε\nB -> ε',
    note: 'Both alternatives of S derive ε. On $, both ask to be selected. The empty string has two parse trees.' },
  { id: 'first-follow', name: 'Consume a, or leave it?', kind: 'FIRST / FOLLOW', focus: 'A', look: 'a', input: 'a',
    source: 'S -> A a\nA -> a | ε',
    note: 'The next a might belong to A, or to the a after A. This grammar is unambiguous, has no left recursion, and is already left factored. It still is not LL(1).' },
  { id: 'nullable-chain', name: 'Empty through another rule', kind: 'LL(1)', focus: 'A', look: 'c', input: 'c',
    source: 'S -> A c\nA -> B | a\nB -> ε',
    note: 'A → B is nullable even though its right-hand side is not written ε. It uses FOLLOW(A) = {c} to choose the branch.' },
  { id: 'factored', name: 'After left factoring', kind: 'LL(1)', focus: 'X', look: 'b', input: 'a b',
    source: 'S -> a X\nX -> b | c',
    note: 'S has one alternative. After consuming a, X can choose with b or c. The language remains {ab, ac}.' },
  { id: 'left-recursion', name: 'An unambiguous left recursion', kind: 'Left recursion', focus: 'E', look: 'id', input: 'id + id',
    source: 'E -> E + T | T\nT -> id',
    note: 'Every string id (+ id)* has a unique left-associated parse. But both alternatives of E can start with id, and expanding E → E + T consumes nothing.' },
  { id: 'recursion-removed', name: 'After removing left recursion', kind: 'LL(1)', focus: 'R', look: '+', input: 'id + id',
    source: 'E -> T R\nR -> + T R | ε\nT -> id',
    note: 'Read T once, then repeat + T through R. At R, + continues and $ stops. Parse-tree shape changes; an AST can still fold the operators to the left.' },
  { id: 'indirect-recursion', name: 'A recursion through another rule', kind: 'Indirect left recursion', focus: 'A', look: 'b', input: 'b a',
    source: 'S -> A\nA -> S a | b',
    note: 'S ⇒ A ⇒ S a returns to S before consuming a token. The cycle is indirect, but the same prediction problem remains.' },
  { id: 'hidden-prefix', name: 'Different names, same first token', kind: 'FIRST / FIRST', focus: 'S', look: 'a', input: 'a c',
    source: 'S -> A c | B d\nA -> a\nB -> a',
    note: 'The written alternatives have no common symbol prefix, yet FIRST(A c) = FIRST(B d) = {a}. Literal left factoring alone does not catch this.' },
  { id: 'ambiguous', name: 'Two trees for the same expression', kind: 'Ambiguous', focus: 'E', look: 'id', input: 'id + id + id',
    source: 'E -> E + E | id',
    note: 'id + id + id can group as (id + id) + id or id + (id + id). This grammar is ambiguous and left recursive. See both trees in the relationship view.' },
  { id: 'exam', name: 'The course exam grammar', kind: 'LL(1)', focus: 'S', look: '1', input: '1 0 1 0',
    source: 'S -> 1 A B | ε\nA -> 1 A C | 0 C\nB -> 0 S\nC -> 1',
    note: 'A full example with recursion, a nullable start symbol, and FOLLOW propagation. Step through 1 0 1 0 to see the accepted derivation.' },
  { id: 'practice', name: 'R and X practice', kind: 'LL(1)', focus: 'R', look: 'a', input: 'a b',
    source: 'R -> a X | ε\nX -> b R | c',
    note: 'On a, expand R. After a b, the next R chooses ε on $. Right recursion does not cause the left-recursion problem.' },
];

export const repairs = [
  { id: 'factor', title: 'Move the choice past the common prefix', before: 'first-first', after: 'factored',
    frames: [
      { grammar: 'S → a b | a c', caption: 'At S with lookahead a, both alternatives compete.', highlights: ['a', 'a'] },
      { grammar: 'S → a ( b | c )', caption: 'Both alternatives require a. Consume that common prefix first.', highlights: ['a'] },
      { grammar: 'S → a X\nX → b | c', caption: 'Make the remaining choice at X, when b or c is visible.', highlights: ['b', 'c'] },
    ],
    general: 'A → γ α | γ β becomes A → γ X; X → α | β.',
    limit: 'Left factoring delays a decision and preserves the language. It does not remove existing ambiguity. Recompute FIRST, FOLLOW, and the table after the rewrite; it does not guarantee LL(1).' },
  { id: 'recursion', title: 'Read a base case before repeating', before: 'left-recursion', after: 'recursion-removed',
    frames: [
      { grammar: 'E → E + T | T\nT → id', caption: 'E ⇒ E + T ⇒ E + T + T. The leftmost E remains and no input is consumed.', highlights: ['E'] },
      { grammar: 'E → T ( + T )*\nT → id', caption: 'The generated strings have one T, followed by zero or more + T parts. This middle frame uses repetition notation, not a CFG production.', highlights: ['T'] },
      { grammar: 'E → T R\nR → + T R | ε\nT → id', caption: 'R expresses the repetition as grammar rules. + continues; $ chooses ε.', highlights: ['+', 'ε'] },
    ],
    general: "A → A α | β becomes A → β A'; A' → α A' | ε, for a nonempty, nonnullable α and a base alternative β.",
    limit: 'Removing immediate left recursion preserves the strings, but changes the parse tree. Indirect or nullable-prefix recursion needs further treatment. Ambiguity and other conflicts may remain.' },
  { id: 'still-conflicts', title: 'A clean-looking grammar can still fail', before: 'first-follow', after: null,
    frames: [
      { grammar: 'S → A a\nA → a | ε', caption: 'No left recursion. No common written prefix. Each valid string, a or a a, has one parse tree.', highlights: ['A'] },
      { grammar: 'FIRST(a) = { a }\nFOLLOW(A) = { a }', caption: 'The same a can start A or follow a vanished A. These sets overlap.', highlights: ['a'] },
      { grammar: 'M[A, a] = { A → a, A → ε }', caption: 'Two productions occupy one cell. The original grammar fails LL(1). S → a X; X → a | ε describes the same language and is LL(1).', highlights: ['a', 'ε'] },
    ],
    general: 'Necessary conditions are not a complete test. Disjoint prediction sets are the deciding condition.',
    limit: 'An LL(1) grammar and an LL(1) language are different claims. A grammar can fail while another grammar for its language succeeds.' },
];
